export default {
  packageManager: "npm",
  reporters: ["html", "clear-text", "progress", "json"],
  testRunner: "vitest",
  vitest: {
    configFile: "vitest.config.ts",
  },
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  excludedMutators: ["BooleanLiteral", "StringLiteral"],
  ignoreStatic: true,
  mutate: [
    "lib/**/*.ts",
    "components/**/*.tsx",
    "app/**/*.tsx",
    "!app/layout.tsx",
    "!app/loading.tsx",
    "!app/not-found.tsx",
    "!app/error.tsx",
    "!app/sitemap.ts",
    "!app/auth/callback/route.ts",
    "!lib/supabase.ts",
    "!**/*.test.{ts,tsx}",
    "!**/*.spec.{ts,tsx}",
  ],
  ignorePatterns: [
    "result",
    "node_modules",
    ".next",
    "coverage",
    "reports",
    ".stryker-tmp",
  ],
  thresholds: { high: 80, low: 60, break: 0 },
};
