on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v6
      - run: |
          nix flake check
  build-github-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build static files
        run: |
          mkdir -p _site/interior-design-editor
          cp packages/cv/index.html _site/index.html
          cp packages/interior-design-editor/{index.html,script.js,style.css} \
            _site/interior-design-editor/
          touch _site/.nojekyll
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site/
  deploy-github-page:
    if: >-
      github.event_name != 'pull_request' &&
      github.ref == format('refs/heads/{0}',
      github.event.repository.default_branch)
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: github-pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [develop, build-github-page]
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
